### ISSUE TITLE
Setting item with child to done cause error

### ISSUE THREAD

**Issue by npfe** [npfe/pursuit#10]
When an element with children is set to "Done", an error is caused in the index page:

``Traceback (most recent call last):
  File "C:\Users\pnic\Documents\web2py\gluon\restricted.py", line 219, in restricted
    exec(ccode, environment)
  File "C:/Users/pnic/Documents/web2py/applications/pursuit/controllers/default.py", line 210, in <module>
  File "C:\Users\pnic\Documents\web2py\gluon\globals.py", line 422, in <lambda>
    self._caller = lambda f: f()
  File "C:/Users/pnic/Documents/web2py/applications/pursuit/controllers/default.py", line 35, in index
    index+=1
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'int'``

**Comment by npfe** [comment]
fixed in #11
